package model;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

public class Purchase {
    private UUID id;
    private Client client;
    private List<Ticket> tickets;
    private double totalAmount;
    private LocalDateTime purchaseTime;
    private PaymentMethod paymentMethod;
    private String transactionId;

    public Purchase(Client client, PaymentMethod paymentMethod) {
        this.id = UUID.randomUUID();
        this.client = client;
        this.tickets = new ArrayList<>();
        this.totalAmount = 0.0;
        this.purchaseTime = LocalDateTime.now();
        this.paymentMethod = paymentMethod;
        this.transactionId = generateTransactionId();
    }

    private String generateTransactionId() {
        // In a real system, this would be generated by the payment processor
        return "TXN-" + id.toString().substring(0, 8);
    }

    public void addTicket(Ticket ticket) {
        tickets.add(ticket);
        totalAmount += ticket.getTicketType().getPrice();
    }

    // Getters and setters
    public UUID getId() {
        return id;
    }

    public Client getClient() {
        return client;
    }

    public List<Ticket> getTickets() {
        return new ArrayList<>(tickets);
    }

    public double getTotalAmount() {
        return totalAmount;
    }

    public LocalDateTime getPurchaseTime() {
        return purchaseTime;
    }

    public PaymentMethod getPaymentMethod() {
        return paymentMethod;
    }

    public String getTransactionId() {
        return transactionId;
    }

    @Override
    public String toString() {
        return String.format("Purchase{id=%s, client='%s %s', tickets=%d, total=%.2f}",
                id, client.getFirstName(), client.getLastName(), tickets.size(), totalAmount);
    }
}